### ISSUE TITLE
Wrong setter name

### ISSUE THREAD

**Issue by dstaroff** [osamarais/micropython_robotics#1]
Why is the frequency setter named `pin`?

https://github.com/osamarais/micropython_robotics/blob/03fa86f3dc582f39b320c9153918b95959204344/servolib.py#L85-L86

**Comment by osamarais** [comment]
Yeah, it seems to be a bug.

This is a very early version of the code. The final developed code (with many more bells and whistles) was submitted to my Professor  and I am unsure of permissions to make it open source.

I put this out here to help anyone willing to get started with micropython to build robots, hopefully this was helpful.

**Comment by osamarais** [comment]
I checked the newer versions of the library I created and this syntax works fine with micropython.
It is possible to create a setter with a different name.


Here is a video of the robots in action if you're interested.
https://www.youtube.com/watch?v=EDdLU_PYheY
